[relaychain]
default_command = "{{RELAYCHAIN_COMMAND}}"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true
chain = "local"

  [parachains.collator]
  ws_port = 9998
  command = "{{PARACHAIN_COMMAND}}"
  validator = true
  args = ["-ldebug,info"]
