[package]
name = "relay-ownership-parachain-client"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5" }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }
subxt = { version = "0.30.1", default-features = false, features = ["native"] }

# Bridge dependencies

bp-bridge-hub-cumulus = { path = "../../primitives/chain-bridge-hub-cumulus" }
bp-header-chain = { path = "../../primitives/header-chain" }
bp-messages = { path = "../../primitives/messages" }
bp-evochain = { path = "../../primitives/chain-evolution" }
bp-polkadot-core = { path = "../../primitives/polkadot-core" }
bp-ownership-parachain = { path = "../../primitives/chain-ownership-parachain" }

bridge-runtime-common = { path = "../../bin/runtime-common" }
relay-substrate-client = { path = "../client-substrate" }

# Substrate Dependencies

sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
sp-weights = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0" }
